2014-01-24 23:21:52,318 [ERROR] django.request: Internal Server Error: /upload/list/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 18, in list
    logr.debug(form)
UnboundLocalError: local variable 'form' referenced before assignment
2014-01-25 01:13:45,645 [ERROR] django.request: Internal Server Error: /upload/list/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 77, in list
    context_instance=RequestContext(request)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 77, in list
    context_instance=RequestContext(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit
2014-01-25 01:14:05,690 [ERROR] django.request: Internal Server Error: /upload/list/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 29, in list
    if request.method == 'POST':
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 29, in list
    if request.method == 'POST':
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit
2014-01-25 13:55:06,574 [ERROR] django.request: Internal Server Error: /dash/dashboard/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/app_magnate/urls.py", line 55, in <module>
    url(r"^zupload/", include("zuploadtest.urls")),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/urls.py", line 3, in <module>
    from zuploadtest import views
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 13, in <module>
    from .forms import UploadModelForm
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/forms.py", line 6, in <module>
    class UploadModelForm(forms.Form):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/forms.py", line 10, in UploadModelForm
    analysis = forms.TextField(max_length=750)
AttributeError: 'module' object has no attribute 'TextField'
2014-01-25 13:57:36,018 [WARNING] django.request: Not Found: /zupload
2014-01-25 13:57:39,791 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 39, in get
    form = self.form_class(initial=self.initial)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/forms.py", line 16, in __init__
    self.fields['first_name'].widget.attrs['id'] = 'super_first'
KeyError: 'first_name'
2014-01-25 14:06:21,224 [WARNING] django.request: Not Found: /zupload/list/
2014-01-25 14:10:26,091 [WARNING] django.request: Not Found: /zupload/list/
2014-01-25 14:11:43,793 [ERROR] django.request: Internal Server Error: /upload/list/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 29, in list
    if request.method == 'POST':
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: uploadtest/list.html
2014-01-25 14:16:05,402 [ERROR] django.request: Internal Server Error: /upload/list/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/uploadtest/views.py", line 29, in list
    if request.method == 'POST':
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: uploadtest/list.html
2014-01-25 14:23:12,732 [ERROR] django.request: Internal Server Error: /zupload/test
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/app_magnate/urls.py", line 54, in <module>
    url(r"^upload/", include("uploadtest.urls")),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named uploadtest.urls
2014-01-25 14:23:59,158 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 41, in get
    return render(request, self.template_name, {'form': form})
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/defaulttags.py", line 424, in render
    raise e
NoReverseMatch: Reverse for 'list' with arguments '()' and keyword arguments '{}' not found.
2014-01-25 14:26:52,865 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/app_magnate/urls.py", line 55, in <module>
    url(r"^zupload/", include("zuploadtest.urls")),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/urls.py", line 4, in <module>
    from .views import survey_index
ImportError: cannot import name survey_index
2014-01-25 14:27:11,174 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 41, in get
    return render(request, self.template_name, {'form': form})
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/defaulttags.py", line 424, in render
    raise e
NoReverseMatch: Reverse for 'zupload_index' with arguments '()' and keyword arguments '{}' not found.
2014-01-25 14:28:25,979 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 41, in get
    return render(request, self.template_name, {'form': form})
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/defaulttags.py", line 424, in render
    raise e
NoReverseMatch: Reverse for 'zupload_index' with arguments '()' and keyword arguments '{}' not found.
2014-01-25 14:29:23,538 [ERROR] django.request: Internal Server Error: /zupload/test_confirm/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 72, in confirmation_index
    return render(request, 'zupload/confirmation.html')
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: zupload/confirmation.html
2014-01-25 17:13:58,359 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 40, in get
    form = self.form_class(initial=self.initial)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/forms.py", line 27, in __init__
    super(UploadModelForm, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-01-25 17:14:46,714 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 40, in get
    form = self.form_class(initial=self.initial)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/forms.py", line 27, in __init__
    super(UploadModelForm, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-01-25 17:16:44,689 [ERROR] django.request: Internal Server Error: /zupload/test/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/zuploadtest/views.py", line 54, in post
    entry.user = form.data['user']
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 405, in __set__
    self.field.name, self.field.rel.to._meta.object_name))
ValueError: Cannot assign "u'root'": "NewUploadModel.user" must be a "User" instance.
2014-01-26 02:18:35,767 [WARNING] django.request: Not Found: /study/
2014-01-26 02:19:14,752 [ERROR] django.request: Internal Server Error: /study/initial_submit/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/study/views.py", line 53, in post
    entry.save()
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/query.py", line 1673, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 130, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1146, "Table 'what_magnatedb.study_studymodel' doesn't exist")
2014-01-27 11:15:12,194 [ERROR] django.request: Internal Server Error: /dash/dashboard/
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/app_magnate/urls.py", line 54, in <module>
    url(r"^study/", include("study.urls")),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/study/urls.py", line 3, in <module>
    from zuploadtest import views
ImportError: No module named zuploadtest
2014-01-27 11:15:12,677 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/app_magnate/urls.py", line 54, in <module>
    url(r"^study/", include("study.urls")),
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/newenv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tehspacecadet_air/Dropbox/Magnate/Application/app_magnate/study/urls.py", line 3, in <module>
    from zuploadtest import views
ImportError: No module named zuploadtest
2014-01-27 11:17:51,181 [WARNING] django.request: Not Found: /favicon.ico
2014-01-31 11:10:33,575 [WARNING] django.request: Not Found: /favicon.ico
2014-02-02 19:41:24,479 [WARNING] django.request: Not Found: /favicon.ico
2014-02-06 15:22:58,304 [WARNING] django.request: Not Found: /accounts/login/
2014-02-06 15:23:00,275 [WARNING] django.request: Not Found: /accounts/login/
2014-02-06 15:23:02,277 [WARNING] django.request: Not Found: /accounts/login/
